CREATE TABLE IF NOT EXISTS books (
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    title   VARCHAR(255)   NOT NULL,
    author  VARCHAR(255)   NOT NULL,
    price   DECIMAL(10, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS ofertas (
    id      BIGINT AUTO_INCREMENT PRIMARY KEY,
    titulo  VARCHAR(255)   NOT NULL,
    preco   DECIMAL(10, 2) NOT NULL,
    criado_em TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
